spring:
  application:
    name: security-service
  config:
    import: optional:configserver:http://localhost:8888

security:
  jjwt: a990baaf02b0eeeb907047f52e7d8f4fbd641ef2263870c3134ea783592b7edf
